title: Taylor Coho # your name (or website title) here
logo: "/images/selfie.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Undergraduate student at the University of Maryland, Baltimore County
  <br><br>
  Environmental Science & Geography 
  <br><br>
  Graduating in the Spring of 2020 
  <br><br>
  GPA: 3.40
  <br><br>
  Experience with:
  GIS, Environmental Sampling,and Ecological Field Surverying 
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
